[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "obsidian"
path = "~/Personal"
startup_command = "nvim"

[[session]]
name = "nvim-config"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "yazi"
